

decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"

release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    find . -name "pom.xml" -exec mvn versions:set "-DnewVersion=${tag}" -f {} \;
    git commit -am "${tag}"
    mvn clean deploy --settings /home/r/settings.xml -Prelease

